### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by YUZHIWANG-bug** [Justin900429/PyTorch-DSSN-MER#4]
Dear author, due to the lack of data set, can I apply for a pre-trained model？

**Comment by YUZHIWANG-bug** [comment]
> Dear author, due to the lack of data set, can I apply for a pre-trained model？
if possible, please contact me : irecalllost@gmail.com

**Comment by Justin900429** [comment]
Hi, currently we don't have the model weights.
You can visit the official implementation for their release model weights, [here](https://github.com/IcedDoggie/DSSN-MER).

**Comment by YUZHIWANG-bug** [comment]
> Hi, currently we don't have the model weights. You can visit the official implementation for their release model weights, [here](https://github.com/IcedDoggie/DSSN-MER).

Thank you very much for your reply, which will be very helpful to me. I wish you a happy life!
